source "http://rubygems.org"

gem "rspec", "~> 3.4"
gem "guard-rspec"
gem "json"
gem "rspec-json_expectations"
gem "rack"
gem "sinatra", require: "sinatra/base"
gem "shotgun"
gem "rack-test"
gem "thin"
gem "wannabe_bool"
gem "sinatra-flash", :require => "sinatra/flash"
gem "rake", "~> 11.2", ">= 11.2.2"
gem "pg", "~> 0.18.4"
gem "pg_tester" 
