$LOAD_PATH << File.expand_path('../../lib', __FILE__)

require "date"
require "json"
require "time_logger/validation"
require "time_logger/repository"
require "time_logger/log_time_entry"
require "time_logger/client"
require "time_logger/employee"
require "time_logger/result"
require "time_logger/validation_date"
require "time_logger/validation_hours_worked"
require "time_logger/validation_menu"
require "time_logger/validation_employee_creation"
require "time_logger/validation_client_creation"
require "time_logger/validation_log_time"
require "time_logger/repository/in_memory/in_memory"
require "time_logger/repository/sql/sql"
require "time_logger/repository_registry"
