$LOAD_PATH << File.expand_path('../lib', __FILE__)
require "date"
require "json"

require "time_logger/console/admin_report"
require "time_logger/console/console_ui"
require "time_logger/console/log_time"
require "time_logger/console/employee_report"
require "time_logger/console/menu_selection"
require "time_logger/console/console_runner"
require "time_logger/console/employee_setup"
require "time_logger/console/employee_creation"
require "time_logger/console/client_creation"
require "time_logger/console/log_hours_worked"
require "time_logger/console/log_timecode"
require "time_logger/console/log_client"
require "time_logger/console/log_date"
require "time_logger"
require "time_logger/console/io_wrapper"
